Make schhist more forgiving if profile or top-level sheet is missing.
- schhist/gitsch2ps: issue a (fatal) error only if .pro and .sch are missing
- schhist/gitsch2ps: exit with success if only one of .pro and .sch is
  missing
- schhist/schhist2web: skip commits for which no Postscript was generated

diff --git a/schhist/gitsch2ps b/schhist/gitsch2ps
--- a/schhist/gitsch2ps
+++ b/schhist/gitsch2ps
@@ -71,15 +71,27 @@ rm -rf "$outdir"
 git clone -q -s -n "$dir/.git" "$tmp" || exit
 ( cd "$tmp" && git checkout -q "$commit"; ) || exit
 
-if [ ! -f "$tmp/$schem" ]; then
-    echo "$schem not found (checked out into $tmp)" 1>&2
+pro=${schem%.sch}.pro
+
+if [ ! -f "$tmp/$pro" -a ! -f "$tmp/$schem" ]; then
+    echo "neither $pro nor $schem found (checked out into $tmp)" 1>&2
     exit 1
+fi
+
+if [ ! -f "$tmp/$schem" ]; then
+    echo "$schem not found (checked out into $tmp), skipping commit" 1>&2
+    exit 0
+fi
+
+if [ ! -f "$tmp/$pro" ]; then
+    echo "$pronot found (checked out into $tmp), skipping commit" 1>&2
+    exit 0
 fi
 
 (
     cd "$sch" || exit
     rm -f *.ps
-    $sanitize_profile "$tmp/${schem%.sch}.pro" || exit
+    $sanitize_profile "$tmp/$pro" || exit
     $sanitize_schem "$tmp/$schem" || exit
     eeschema --plot "$tmp/$schem"
 ) || exit
